const assert=require('assert');
global.window=global;global.document=null;require('../js/year-report.js');
const state={language:'en',currentYear:2026,schedule:[{month:0,congregation:'New London Spanish',status:'confirmed',note:'Fixed'}],planning:[{year:2031,rows:[{month:5,congregation:'Future Spanish',confirmed:false,note:''}]}],congregations:[{name:'NewLondon Spanish',coordinator:'John Doe',phone:'860-555-0100',email:'john@example.com'}]};
let model=TalkYearReport.buildModel(state,2026,false);
assert.strictEqual(model.rows[0].coordinator,'');
assert(!TalkYearReport.tableHtml(model).includes('john@example.com'));
model=TalkYearReport.buildModel(state,2026,true);
assert.strictEqual(model.rows[0].coordinator,'John Doe');
assert(TalkYearReport.textReport(model).includes('860-555-0100'));
const future=TalkYearReport.buildModel(state,2031,true);
assert.strictEqual(future.rows[0].month,'June');
const mismatchedState={language:'en',currentYear:2026,schedule:[{month:0,congregation:'Example Spanish',contact:'Different Brother',status:'confirmed',note:''}],planning:[],congregations:[{name:'Example Spanish',coordinator:'Directory Brother',phone:'860-555-0199',email:'directory@example.com'}]};
const mismatched=TalkYearReport.buildModel(mismatchedState,2026,true);
assert.strictEqual(mismatched.rows[0].coordinator,'Different Brother');
assert.strictEqual(mismatched.rows[0].phone,'','phone must not be paired with a different person');
assert.strictEqual(mismatched.rows[0].email,'','email must not be paired with a different person');
assert.strictEqual(mismatched.rows[0].contactUnmatched,true);
const printable=TalkYearReport.printableDocument(model);
assert(printable.includes('Print / Save PDF'));
assert(printable.includes('<table>'));
assert(printable.includes('@media print'));
console.log('year report tests: passed');
